name: Docker Image CI for GHCR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push image
      run:
        docker login --username yukitoki02 --password ${{ secrets.GH_PERSONALACCTOKEN }} ghcr.io
        docker build . -t ghcr.io/toru45/dicodingintermedietenoteapi:latest
        docker push ghcr.io/toru45/dicodingintermedietenoteapi:latest
