name: Docker Image CI for GHCR

on:
  push

jobs:
  build-and_piblish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docekr login
      run:
        docker login --username yukitoki02 --password ${{ secrets.GH_PERSONALACCTOKEN }} ghcr.io
    - name: Docker build
      run:
        docker build . --tag ghcr.io/toru45/dicodingintermedietenoteapi:latest
    - name: Docker push
      run:
        docker push ghcr.io/toru45/dicodingintermedietenoteapi:latest